apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversaotemperatura
spec:
  replicas: 3
  selector:
    matchLabels:
      app: temperatura
  template:
    metadata:
      name: conversaotemperatura
      labels:
        app: temperatura
    spec:
      containers:
        - name: temperatura
          image: rxcxsx/conversao-temperatura:latest
          ports:
          - containerPort: 8080
